# Generated by Django 4.2.20 on 2025-04-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('parent_code', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_position', models.CharField(blank=True, choices=[('L', 'left'), ('R', 'right')], max_length=20, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
